// <auto-generated />
namespace LTQL_quanlythuvien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_alter_sdt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_alter_sdt));
        
        string IMigrationMetadata.Id
        {
            get { return "202105111226378_create_alter_sdt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
